#!/bin/bash
#SBATCH --job-name="tests/test-task"
#SBATCH --output="saws-tests.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 00:15:00

#SET the number of openmp threads
export OMP_NUM_THREADS=24

#Run the job using mpirun_rsh
srun /home/hannahc/saws/tests/test-tasktree
